#!/bin/sh
# Name : AntiPorn
# description: Block Porno Sites 
# Tested on: MacOS, Linux, Windows coming soon..
# Date : April 2022
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
Banner(){
  echo "$BLUE
       d8888          888    d8b 8888888b.                           
      d88888          888    Y8P 888   Y88b                          
     d88P888          888        888    888                          
    d88P 888 88888b.  888888 888 888   d88P .d88b.  888d888 88888b.  
   d88P  888 888  88b 888    888 8888888P  d88  88b 888P    888  88b 
  d88P   888 888  888 888    888 888       888  888 888     888  888 
 d8888888888 888  888 Y88b.  888 888       Y88  88P 888     888  888 
d88P     888 888  888  Y888 888 888         Y88P   888     888  888 ${cyan}
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒ https://www.github.com/Anlominus/AntiPorn"
}
logo="$(Banner)"

Prompt(){
  echo ""
  echo "  ${orange}  ┌──[${blue}Anlominus${purple}👽${red}HacKits${cyan}$~${orange}]${cyan}"
  echo "  ${orange}  └──╼${green}"
}
Backup(){
  echo "# Backup Old /etc/hosts To /etc/hosts_old"
  sleep 1
  `sudo cp /etc/hosts /etc/hosts_old`
  sleep 2
  echo "# Backup Done Successfully !"  
  sleep 1
  }
  
Rename(){
  echo "# Renaming old AntiPornHosts To hosts"
  sleep 1
  `sudo mv PornHosts hosts`
  sleep 2
  echo "# Renaming Done Successfully !"  
  sleep 1
  }
  
Replace(){
  echo "# Replacing new hosts With old /etc/hosts"
  sleep 1
  `sudo cp hosts /etc/hosts`
  sleep 2
  echo "# Replacing Done Successfully !"  
  sleep 1
  }
 
Intall(){
  clear 
  sleep 1
  Backup
  sleep 1
  Rename
  sleep 1
  Replace
  sleep 1
  echo "# AntiPorn Installing Successfully !"  
  sleep 5
}


# this is the main function
Menu() {
  while true; do
    clear
    echo "$(banner)"
    echo " "
    echo "${cyan}     [a] ${green} Automating Install AntiPorn"    
    echo "${cyan}         ${green}[ Manual Installing ]"
    echo "${cyan}     [1] ${green} Backup old Hosts to hosts_old "
    echo "${cyan}     [2] ${green} Rename PornHosts to hosts"
    echo "${cyan}     [3] ${green} Replace & Install"
    echo "${cyan}     [4] ${green} Update HacKits"
    echo "${cyan}     [5] ${green} About us"
    echo "${cyan}     [x] ${green} Exit"
    echo "$(Prompt)"
    read cmd
    case ${cmd} in
      a)
        install
      ;;
      1)
        Backup
      ;;
      2)
        Rename
      ;;
      3)
        Replace
      ;;
      4)
        about
      ;;
      x|exit|Exit)
        echo "${green}Exiting ....${nc}"
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;
    esac
  done
}

Menu
